"""Cause code knowledge base for troubleshooting and root cause analysis.

Each entry: name, meaning (plain English), likely root causes, checks, category,
spec reference. Codes and names follow TS 24.301 (EMM/ESM) and TS 24.501
(5GMM/5GSM). The explanations are engineering guidance, not spec text.
"""


def _c(name, meaning, causes=(), checks=(), cat="protocol"):
    return {"name": name, "meaning": meaning, "causes": list(causes), "checks": list(checks), "category": cat}


_PROTOCOL_ERRORS = {
    95: _c("Semantically incorrect message", "The receiver understood the message format but its content is inconsistent.",
           ["UE or network implementation bug", "Interop issue between UE firmware and core vendor"],
           ["Compare the IE values against the spec conditions", "Check for a recent UE firmware or core software change"]),
    96: _c("Invalid mandatory information", "A mandatory IE is missing or malformed.",
           ["Encoding bug in the sender", "Truncated message in the log"],
           ["Verify the full hex was captured", "Decode the peer message and check every mandatory IE"]),
    97: _c("Message type non-existent or not implemented", "The receiver does not support this message type.",
           ["Feature not supported by peer", "Release mismatch between UE and network"],
           ["Check the UE and network 3GPP release / feature support"]),
    98: _c("Message type not compatible with the protocol state", "The message arrived in a state where it is not expected.",
           ["State mismatch between UE and network (for example after a lost message)", "Race between procedures"],
           ["Look at the preceding messages for a missing response or a collision"]),
    99: _c("Information element non-existent or not implemented", "An IE is not supported by the receiver.",
           ["Release mismatch", "Optional feature not implemented"],
           ["Identify the IE and check feature support on both sides"]),
    100: _c("Conditional IE error", "A conditional IE is present when it should not be, or missing when required.",
            ["Encoding bug", "Feature negotiation mismatch"],
            ["Check the condition rules for the IE in the spec"]),
    101: _c("Message not compatible with the protocol state", "The message content conflicts with the current state.",
            ["State machine mismatch", "Collision of procedures"],
            ["Check the procedure ordering in the log"]),
    111: _c("Protocol error, unspecified", "Generic protocol error with no specific cause.",
            ["Implementation specific failure"],
            ["Collect network side traces (S1AP/NGAP, MME/AMF logs) to find the real reason"]),
}

EMM_CAUSES = {
    2: _c("IMSI unknown in HSS", "The subscriber is not provisioned in the HSS / HLR.",
          ["SIM not provisioned or deactivated", "Wrong IMSI range routed to this HSS", "Test SIM on a commercial network"],
          ["Verify the IMSI is provisioned and active in HSS", "Check IMSI range routing on the MME / DRA"], "subscription"),
    3: _c("Illegal UE", "The network considers the UE invalid, usually after an authentication failure.",
          ["Authentication failed (wrong K / OPc on the SIM)", "UE blacklisted"],
          ["Check SIM K / OPc against HSS", "Look for Authentication Reject earlier in the log"], "subscription"),
    5: _c("IMEI not accepted", "The device IMEI was rejected (EIR check).",
          ["Device IMEI blacklisted or not whitelisted", "Invalid IMEI written on the device"],
          ["Check the IMEI written to the device", "Check EIR configuration"], "subscription"),
    6: _c("Illegal ME", "The mobile equipment is not allowed on the network.",
          ["IMEI blacklisted in EIR", "Unapproved device type"],
          ["Check EIR status of the IMEI"], "subscription"),
    7: _c("EPS services not allowed", "Subscription does not allow LTE (EPS) service.",
          ["No EPS / LTE subscription for the IMSI", "Wrong APN or access restriction data"],
          ["Check subscriber profile in HSS (Access-Restriction-Data, network access mode)"], "subscription"),
    8: _c("EPS services and non-EPS services not allowed", "Subscription allows neither LTE nor CS service.",
          ["Subscription barred or not provisioned"],
          ["Check subscriber status in HSS / HLR"], "subscription"),
    9: _c("UE identity cannot be derived by the network", "The network could not resolve the GUTI / S-TMSI the UE used.",
          ["MME restart or context lost", "GUTI from another MME pool that cannot be reached"],
          ["UE should re-attach with IMSI; check whether the next Attach succeeds", "Check MME pool and S10 connectivity"], "network"),
    10: _c("Implicitly detached", "The network has already detached the UE (for example after the mobile reachable timer expired).",
           ["UE was out of coverage longer than the implicit detach timer", "MME context cleared"],
           ["Expect the UE to re-attach", "Check T3412 vs network implicit detach timer"], "network"),
    11: _c("PLMN not allowed", "The UE is not allowed to use this PLMN.",
           ["Roaming not permitted", "Wrong PLMN selected by the UE (forbidden list)"],
           ["Check roaming agreements and the UE PLMN selection", "Check the SIM forbidden PLMN list"], "subscription"),
    12: _c("Tracking Area not allowed", "The UE may not access this tracking area.",
           ["Regional subscription / area restriction", "TA restriction on the MME"],
           ["Check area restrictions in HSS and MME TA lists"], "subscription"),
    13: _c("Roaming not allowed in this tracking area", "Roaming is restricted in this TA.",
           ["National roaming restriction", "TA-based roaming policy"],
           ["Check roaming restriction policy for the TA"], "subscription"),
    14: _c("EPS services not allowed in this PLMN", "LTE is not allowed for the UE in this PLMN.",
           ["No LTE roaming agreement", "PLMN-specific restriction"],
           ["Check roaming LTE agreement / HSS restriction"], "subscription"),
    15: _c("No suitable cells in tracking area", "The UE must search for another TA in the same PLMN.",
           ["TA restriction for this subscriber", "Wrong TAC configured on the cell", "CSG or access restriction"],
           ["Verify TAC configuration of the serving cell", "Check TA restriction for the subscriber"], "mobility"),
    16: _c("MSC temporarily not reachable", "Combined attach/TAU succeeded for EPS only; CS (SGs) side failed.",
           ["SGs interface to MSC down", "MSC overload"],
           ["Check SGs association status between MME and MSC", "CSFB calls will fail until fixed"], "network"),
    17: _c("Network failure", "A failure in the core network (MME, HSS, SGW or PGW).",
           ["HSS / S6a timeout", "SGW / PGW unreachable or rejecting the session", "Core overload"],
           ["Check MME logs for S6a / S11 errors", "Check SGW / PGW health and create session responses"], "network"),
    18: _c("CS domain not available", "CS services (CSFB / SMS over SGs) are not available.",
           ["No SGs association", "Subscription without CS", "Network is VoLTE only"],
           ["If voice must work, verify VoLTE / IMS registration", "Check SGs and CS subscription"], "network"),
    19: _c("ESM failure", "The attach failed because the default bearer (PDN connection) could not be set up.",
           ["APN wrong or not subscribed", "PGW rejected the session", "IP pool exhausted"],
           ["Check the ESM cause in the embedded ESM message", "Verify APN configuration on UE and in HSS"], "network"),
    20: _c("MAC failure", "UE detected that the network authentication token (AUTN) MAC is wrong.",
           ["K / OPc mismatch between SIM and HSS", "Fake or misconfigured network", "Wrong SIM profile"],
           ["Check K / OPc / AMF in HSS against SIM", "Confirm the UE is on the intended network"], "security"),
    21: _c("Synch failure", "Sequence number (SQN) out of range between SIM and HSS.",
           ["SQN desynchronisation after SIM reuse in a lab", "HSS SQN reset"],
           ["Usually self-healing via AUTS resync; if repeated, check HSS SQN handling"], "security"),
    22: _c("Congestion", "The network is congested and rejected the request.",
           ["MME overload / NAS level congestion control", "APN based congestion"],
           ["Check T3346 back-off value in the message", "Check MME load and overload control"], "congestion"),
    23: _c("UE security capabilities mismatch", "Replayed UE security capabilities did not match.",
           ["UE capability changed or corrupted", "MME bug"],
           ["Compare UE network capability in Attach with the replayed value in Security Mode Command"], "security"),
    24: _c("Security mode rejected, unspecified", "UE rejected the security mode command.",
           ["Unsupported algorithm selected", "Integrity check failed"],
           ["Check selected EEA / EIA vs UE capability"], "security"),
    25: _c("Not authorized for this CSG", "UE not a member of the closed subscriber group.",
           ["CSG membership missing"], ["Check CSG subscription"], "subscription"),
    26: _c("Non-EPS authentication unacceptable", "UMTS-only (non-EPS) authentication vector not acceptable.",
           ["SIM or HSS returned a non-EPS vector (AMF separation bit 0)"],
           ["Check HSS AMF field and USIM type"], "security"),
    31: _c("Redirection to 5GCN required", "The network asks the UE to use 5GC (N1 mode) instead of EPC.",
           ["Core steering policy"], ["Check UE N1 mode support and 5G subscription"], "mobility"),
    35: _c("Requested service option not authorized in this PLMN", "Service option is not allowed here.",
           ["Subscription restriction"], ["Check service option policy"], "subscription"),
    39: _c("CS service temporarily not available", "CS fallback temporarily not possible.",
           ["MSC busy or SGs paging failure"], ["Retry after back-off, check MSC"], "network"),
    40: _c("No EPS bearer context activated", "Service request rejected because no bearer is active.",
           ["UE and network bearer state mismatch"], ["UE should re-attach; check bearer status IE"], "network"),
    42: _c("Severe network failure", "The network has a severe failure; UE should not retry soon.",
           ["Core outage"], ["Check core network alarms"], "network"),
    78: _c("PLMN not allowed to operate at the present UE location", "PLMN not allowed at this location (satellite / regulatory).",
           ["Location-based restriction"], ["Check location policy"], "subscription"),
}
EMM_CAUSES.update(_PROTOCOL_ERRORS)

ESM_CAUSES = {
    8: _c("Operator determined barring", "Session barred by operator policy.", ["Subscriber barred for data"],
          ["Check ODB settings in HSS"], "subscription"),
    26: _c("Insufficient resources", "Network lacks resources for the bearer.", ["PGW / SGW resource limit", "IP pool exhausted"],
           ["Check PGW capacity and IP pools"], "congestion"),
    27: _c("Missing or unknown APN", "The requested APN is unknown or not configured.",
           ["Wrong APN on the device", "APN not in subscription", "DNS cannot resolve the APN"],
           ["Compare device APN with subscription APN list", "Check APN DNS resolution on MME"], "config"),
    28: _c("Unknown PDN type", "Requested PDN type not recognised.", ["Wrong PDN type requested"],
           ["Check device IP type setting (IPv4 / IPv6 / IPv4v6)"], "config"),
    29: _c("User authentication or authorization failed", "PDN authentication (PAP / CHAP / RADIUS) failed.",
           ["Wrong APN username / password", "AAA rejection"], ["Check APN credentials and AAA logs"], "subscription"),
    30: _c("Request rejected by Serving GW or PDN GW", "SGW / PGW rejected the session creation.",
           ["PGW policy (PCRF / Gx) failure", "SGW / PGW misconfiguration"], ["Check S11 / S5 create session response cause"], "network"),
    31: _c("Request rejected, unspecified", "Request rejected without a specific reason.", ["Core policy or implementation specific"],
           ["Collect MME and PGW traces"], "network"),
    32: _c("Service option not supported", "Requested service option not supported.", ["Feature not supported"], [], "config"),
    33: _c("Requested service option not subscribed", "The subscriber is not allowed this APN or service.",
           ["APN not in subscription", "QoS or service not subscribed"], ["Check APN-Configuration in HSS"], "subscription"),
    34: _c("Service option temporarily out of order", "Service temporarily unavailable.", ["Temporary core issue"], [], "network"),
    35: _c("PTI already in use", "Procedure transaction identity collision.", ["UE reused a PTI"], [], "protocol"),
    36: _c("Regular deactivation", "Normal bearer / PDN deactivation.", ["Normal release"], [], "network"),
    37: _c("EPS QoS not accepted", "Requested QoS rejected.", ["QoS beyond subscription"], ["Check requested vs subscribed QoS"], "config"),
    38: _c("Network failure", "Core network failure during session handling.", ["PGW / PCRF failure"], ["Check PGW / PCRF logs"], "network"),
    39: _c("Reactivation requested", "Network asks the UE to re-establish the PDN connection.", ["PGW relocation", "Policy change"],
           ["Expect a new PDN Connectivity Request"], "network"),
    43: _c("Invalid EPS bearer identity", "Bearer ID not valid.", ["Bearer state mismatch"], [], "protocol"),
    50: _c("PDN type IPv4 only allowed", "Only IPv4 is allowed for this APN.", ["APN configured IPv4 only"],
           ["Set device PDN type to IPv4 or update subscription"], "config"),
    51: _c("PDN type IPv6 only allowed", "Only IPv6 is allowed for this APN.", ["APN configured IPv6 only"],
           ["Set device PDN type to IPv6 or update subscription"], "config"),
    52: _c("Single address bearers only allowed", "Dual stack not allowed on one bearer.", ["Network does not support IPv4v6 bearers"],
           ["UE may open a second PDN connection for the other IP version"], "config"),
    53: _c("ESM information not received", "The network expected ESM information (APN / PCO) but did not get it.",
           ["UE did not respond to ESM Information Request", "ESM information transfer flag issue"],
           ["Check ESM Information Request / Response exchange"], "protocol"),
    54: _c("PDN connection does not exist", "The referenced PDN connection is unknown.", ["State mismatch"], [], "protocol"),
    55: _c("Multiple PDN connections for a given APN not allowed", "Only one PDN connection per APN.",
           ["UE requested a second connection to the same APN"], [], "config"),
    56: _c("Collision with network initiated request", "UE request collided with a network request.", ["Race condition"], [], "protocol"),
    57: _c("PDN type IPv4v6 only allowed", "Only dual stack allowed.", ["APN policy"], [], "config"),
    59: _c("Unsupported QCI value", "QCI not supported.", ["Unsupported QoS class"], [], "config"),
    65: _c("Maximum number of EPS bearers reached", "No more bearers can be set up.", ["UE already has the maximum bearers"], [], "congestion"),
    66: _c("Requested APN not supported in current RAT and PLMN combination", "APN not allowed on this RAT / PLMN.",
           ["APN restricted to another RAT"], ["Check APN RAT restrictions"], "subscription"),
    112: _c("APN restriction value incompatible with active EPS bearer context", "APN restriction conflict.",
            ["Conflicting APN restriction values"], [], "config"),
    113: _c("Multiple accesses to a PDN connection not allowed", "Multi-access not allowed.", [], [], "config"),
}
ESM_CAUSES.update({k: v for k, v in _PROTOCOL_ERRORS.items() if k not in ESM_CAUSES})

FGMM_CAUSES = {
    3: _c("Illegal UE", "The network considers the UE invalid, usually after authentication failure.",
          ["Wrong K / OPc on the SIM", "SUPI not allowed"], ["Check UDM / AUSF authentication results"], "subscription"),
    5: _c("PEI not accepted", "Permanent equipment identity (IMEI) rejected.", ["IMEI blacklisted (5G-EIR)"],
          ["Check 5G-EIR status"], "subscription"),
    6: _c("Illegal ME", "Mobile equipment not allowed.", ["IMEI blacklisted"], ["Check 5G-EIR"], "subscription"),
    7: _c("5GS services not allowed", "Subscription does not allow 5G service.",
          ["No 5G subscription", "UDM access restriction (NR not allowed)"],
          ["Check UDM subscription (RAT restrictions, core network type restriction)"], "subscription"),
    9: _c("UE identity cannot be derived by the network", "5G-GUTI could not be resolved.",
          ["AMF context lost", "Old AMF unreachable"], ["UE should register with SUCI; check next Registration"], "network"),
    10: _c("Implicitly de-registered", "Network already de-registered the UE.", ["Mobile reachable timer expired"],
           ["Expect a new initial registration"], "network"),
    11: _c("PLMN not allowed", "UE not allowed in this PLMN.", ["Roaming not permitted", "Forbidden PLMN"],
           ["Check roaming agreements and UE PLMN selection"], "subscription"),
    12: _c("Tracking area not allowed", "UE not allowed in this TA.", ["Area restriction"], ["Check UDM area restriction"], "subscription"),
    13: _c("Roaming not allowed in this tracking area", "Roaming restricted in this TA.", ["Roaming policy"], [], "subscription"),
    15: _c("No suitable cells in tracking area", "UE must look for another TA.", ["TA restriction", "TAC misconfiguration"],
           ["Verify TAC of the serving cell and TA restrictions"], "mobility"),
    20: _c("MAC failure", "UE found the network authentication MAC wrong.", ["K / OPc mismatch", "Rogue or misconfigured network"],
           ["Check K / OPc / AMF in UDM / ARPF against SIM"], "security"),
    21: _c("Synch failure", "SQN out of range between SIM and UDM.", ["SQN desync after lab reuse"],
           ["Normally recovered by resynchronisation; investigate if repeated"], "security"),
    22: _c("Congestion", "Network congested; UE must back off.", ["AMF overload / NAS congestion control", "Slice congestion"],
           ["Check the T3346 back-off timer value", "Check AMF / slice load"], "congestion"),
    23: _c("UE security capabilities mismatch", "Replayed UE security capabilities do not match.", ["Capability mismatch"],
           ["Compare UE security capability in Registration Request and Security Mode Command"], "security"),
    24: _c("Security mode rejected, unspecified", "UE rejected the security mode command.", ["Unsupported algorithm", "Integrity failure"],
           ["Check selected 5G-EA / 5G-IA vs UE capability"], "security"),
    26: _c("Non-5G authentication unacceptable", "Authentication vector not valid for 5G.", ["AMF separation bit not set in vector"],
           ["Check UDM authentication vector generation"], "security"),
    27: _c("N1 mode not allowed", "UE is not allowed to use 5GC (N1 mode).", ["Subscription without 5GC access"],
           ["Check core network type restriction in UDM"], "subscription"),
    28: _c("Restricted service area", "UE is in a restricted service area.", ["Service area restriction"], [], "subscription"),
    31: _c("Redirection to EPC required", "Network steers the UE to EPC (LTE core).", ["Core steering policy", "No 5GC subscription"],
           ["Check UE behaviour after redirection (TAU / Attach on LTE)"], "mobility"),
    43: _c("LADN not available", "Local area data network not available here.", ["UE outside LADN service area"], [], "mobility"),
    62: _c("No network slices available", "None of the requested slices (S-NSSAI) can be served.",
           ["Requested NSSAI not subscribed", "Slice not supported in this TA"],
           ["Compare Requested NSSAI with Subscribed / Allowed NSSAI", "Check NSSF / AMF slice configuration"], "config"),
    65: _c("Maximum number of PDU sessions reached", "No more PDU sessions can be set up.", ["UE already has the maximum"], [], "congestion"),
    67: _c("Insufficient resources for specific slice and DNN", "Slice + DNN congestion.", ["Slice / DNN overload"],
           ["Check back-off timer and slice load"], "congestion"),
    69: _c("Insufficient resources for specific slice", "Slice congestion.", ["Slice overload"], ["Check slice capacity"], "congestion"),
    71: _c("ngKSI already in use", "Key set identifier collision.", ["Security context mismatch"], [], "security"),
    72: _c("Non-3GPP access to 5GCN not allowed", "Non-3GPP access not allowed.", ["Subscription"], [], "subscription"),
    73: _c("Serving network not authorized", "Serving network not authorized by home network.", ["Roaming / SN name mismatch"],
           ["Check serving network name used in authentication"], "subscription"),
    74: _c("Temporarily not authorized for this SNPN", "SNPN access temporarily refused.", [], [], "subscription"),
    75: _c("Permanently not authorized for this SNPN", "SNPN access refused.", [], [], "subscription"),
    76: _c("Not authorized for this CAG or authorized for CAG cells only", "CAG access mismatch.", ["CAG configuration"], [], "subscription"),
    77: _c("Wireline access area not allowed", "Wireline area not allowed.", [], [], "subscription"),
    78: _c("PLMN not allowed to operate at the present UE location", "Location based PLMN restriction.", [], [], "subscription"),
    79: _c("UAS services not allowed", "UAS (drone) services not allowed.", [], [], "subscription"),
    90: _c("Payload was not forwarded", "AMF could not forward the NAS payload (for example to SMF).",
           ["SMF not reachable", "DNN / slice not supported"], ["Check AMF to SMF selection and the 5GSM message"], "network"),
    91: _c("DNN not supported or not subscribed in the slice", "The DNN is not allowed for this S-NSSAI.",
           ["Wrong DNN on device", "DNN missing in subscription for the slice"],
           ["Compare device DNN with UDM subscribed DNNs for the slice"], "config"),
    92: _c("Insufficient user-plane resources for the PDU session", "Not enough UP resources.", ["gNB / UPF resource shortage"],
           ["Check gNB admission control and UPF load"], "congestion"),
}
FGMM_CAUSES.update(_PROTOCOL_ERRORS)

FGSM_CAUSES = {
    8: _c("Operator determined barring", "Session barred by operator policy.", [], ["Check subscription barring"], "subscription"),
    26: _c("Insufficient resources", "Network lacks resources for the PDU session.", ["SMF / UPF capacity", "IP pool exhausted"],
           ["Check SMF / UPF capacity and IP pools"], "congestion"),
    27: _c("Missing or unknown DNN", "Requested DNN is unknown.", ["Wrong DNN on device", "DNN not configured on SMF"],
           ["Compare device DNN with SMF / UDM configuration"], "config"),
    28: _c("Unknown PDU session type", "PDU session type not recognised.", ["Wrong session type requested"], [], "config"),
    29: _c("User authentication or authorization failed", "Secondary authentication failed.", ["DN-AAA rejection"],
           ["Check DN-AAA credentials"], "subscription"),
    31: _c("Request rejected, unspecified", "Request rejected without a specific reason.", ["SMF policy / PCF decision"],
           ["Collect SMF / PCF traces"], "network"),
    32: _c("Service option not supported", "Requested service not supported.", [], [], "config"),
    33: _c("Requested service option not subscribed", "DNN or service not in subscription.", ["DNN not subscribed"],
           ["Check UDM session management subscription data"], "subscription"),
    35: _c("PTI already in use", "PTI collision.", [], [], "protocol"),
    36: _c("Regular deactivation", "Normal PDU session release.", ["Normal release"], [], "network"),
    37: _c("5GS QoS not accepted", "Requested QoS rejected.", ["QoS beyond subscription"], [], "config"),
    38: _c("Network failure", "Failure in SMF / UPF / PCF.", ["Core failure"], ["Check SMF / UPF logs"], "network"),
    39: _c("Reactivation requested", "Network asks the UE to re-establish the PDU session.", ["UPF relocation"], [], "network"),
    43: _c("Invalid PDU session identity", "PDU session ID not valid.", ["State mismatch"], [], "protocol"),
    46: _c("Out of LADN service area", "UE outside the LADN service area.", [], [], "mobility"),
    50: _c("PDU session type IPv4 only allowed", "Only IPv4 allowed.", ["DNN policy"], ["Set device to IPv4"], "config"),
    51: _c("PDU session type IPv6 only allowed", "Only IPv6 allowed.", ["DNN policy"], ["Set device to IPv6"], "config"),
    54: _c("PDU session does not exist", "Referenced PDU session unknown to the network.", ["State mismatch after mobility"], [], "protocol"),
    57: _c("PDU session type IPv4v6 only allowed", "Only dual stack allowed.", [], [], "config"),
    58: _c("PDU session type Unstructured only allowed", "Only unstructured allowed.", [], [], "config"),
    59: _c("Unsupported 5QI value", "5QI not supported.", [], [], "config"),
    61: _c("PDU session type Ethernet only allowed", "Only Ethernet allowed.", [], [], "config"),
    67: _c("Insufficient resources for specific slice and DNN", "Slice + DNN congestion.", ["Slice / DNN overload"],
           ["Check back-off timer"], "congestion"),
    68: _c("Not supported SSC mode", "Requested SSC mode not supported.", [], [], "config"),
    69: _c("Insufficient resources for specific slice", "Slice congestion.", [], [], "congestion"),
    70: _c("Missing or unknown DNN in a slice", "DNN not available in the selected slice.", ["DNN / S-NSSAI mismatch"],
           ["Check DNN per S-NSSAI in subscription"], "config"),
    81: _c("Invalid PTI value", "PTI value not valid.", [], [], "protocol"),
    82: _c("Maximum data rate per UE for user-plane integrity protection is too low", "UP integrity rate too low.", [], [], "config"),
    83: _c("Semantic error in the QoS operation", "QoS rule semantic error.", [], [], "protocol"),
    84: _c("Syntactical error in the QoS operation", "QoS rule syntax error.", [], [], "protocol"),
    85: _c("Invalid mapped EPS bearer identity", "Mapped EBI invalid.", [], [], "protocol"),
}
FGSM_CAUSES.update({k: v for k, v in _PROTOCOL_ERRORS.items() if k not in FGSM_CAUSES})

TABLES = {"EMM": (EMM_CAUSES, "TS 24.301 Annex A"), "ESM": (ESM_CAUSES, "TS 24.301 Annex B"),
          "5GMM": (FGMM_CAUSES, "TS 24.501 Annex A"), "5GSM": (FGSM_CAUSES, "TS 24.501 Annex B")}


def lookup(kind, code):
    table, ref = TABLES[kind]
    e = table.get(code)
    if e is None:
        return {"name": f"Cause #{code}", "meaning": "Cause value not in the knowledge base.",
                "causes": [], "checks": [f"Look up cause #{code} in {ref}"], "category": "protocol",
                "code": code, "ref": ref}
    out = dict(e)
    out["code"] = code
    out["ref"] = ref
    return out


# --- RRC level causes --------------------------------------------------------

REESTABLISHMENT_CAUSES = {
    "reconfigurationFailure": {
        "title": "UE could not apply an RRC reconfiguration",
        "meaning": "The UE received a reconfiguration it could not comply with and re-established the connection.",
        "causes": ["Network sent a configuration outside UE capability (bands, CA combo, MIMO layers)",
                   "Inconsistent or invalid configuration (for example wrong SCell or measurement IDs)",
                   "UE firmware bug in applying the configuration"],
        "checks": ["Decode the reconfiguration right before this message", "Compare it with UE capability",
                   "Check for repeated failures with the same reconfiguration"]},
    "handoverFailure": {
        "title": "Handover failed (T304 expiry)",
        "meaning": "The UE did not complete random access on the target cell before T304 expired.",
        "causes": ["Target cell too weak or high interference", "Wrong target PCI / frequency in the handover command",
                   "RACH configuration problem on the target", "Late handover (serving already too weak)"],
        "checks": ["Check target cell RSRP in the last measurement report", "Check RACH configuration and PRACH power",
                   "Tune A3 offset / time-to-trigger if handovers are late"]},
    "otherFailure": {
        "title": "Radio link failure",
        "meaning": "The UE declared radio link failure (T310 expiry, max RLC retransmissions or random access problem).",
        "causes": ["Coverage hole or sudden signal drop", "Uplink limited (UE at max power)", "Strong interference",
                   "Missed or late handover"],
        "checks": ["Check RSRP / RSRQ / SINR before the failure", "Check UE transmit power headroom",
                   "Review neighbour relations and handover thresholds"]},
}

SCG_FAILURE_TYPES = {
    "t310-Expiry": ("SCG radio link failure (T310 expiry)", "NR leg lost synchronisation; coverage or interference on the NR cell."),
    "randomAccessProblem": ("SCG random access problem", "UE could not complete RACH on the NR PSCell; weak NR coverage, wrong RACH config or UL power limit."),
    "rlc-MaxNumRetx": ("SCG RLC max retransmissions", "Uplink on NR leg failing; UL coverage limit or interference."),
    "synchReconfigFailureSCG": ("SCG addition / change failure (T304 expiry)", "UE failed to access the NR PSCell during SCG addition or change."),
    "scg-ReconfigFailure": ("SCG reconfiguration failure", "UE could not apply the NR SCG configuration; check config vs UE capability."),
    "scg-reconfigFailure": ("SCG reconfiguration failure", "UE could not apply the NR SCG configuration; check config vs UE capability."),
    "srb3-IntegrityFailure": ("SRB3 integrity failure", "Integrity check failed on SRB3; security key mismatch."),
    "t312-Expiry-r16": ("T312 expiry on SCG", "Fast RLF detection triggered on the SCG."),
    "lbt-Failure-r16": ("LBT failure on SCG", "Listen-before-talk failure on unlicensed NR."),
    "beamFailureRecoveryFailure-r16": ("Beam failure recovery failure", "UE could not recover the beam on the NR PSCell."),
    "bh-RLF-r16": ("Backhaul RLF", "IAB backhaul radio link failure."),
    "other-r16": ("Other SCG failure", "Unspecified SCG failure."),
}

RLF_CAUSES = {
    "t310-Expiry": "Downlink out-of-sync for longer than T310",
    "randomAccessProblem": "Random access did not succeed",
    "rlc-MaxNumRetx": "Maximum RLC retransmissions reached (usually uplink limited)",
    "t312-Expiry-r12": "T312 expired during measurement reporting",
    "t312-Expiry": "T312 expired during measurement reporting",
    "beamFailureRecoveryFailure": "Beam failure recovery failed",
    "lbt-Failure-r16": "Listen-before-talk failure",
}

ESTABLISHMENT_CAUSES = {
    "emergency": "Emergency call", "highPriorityAccess": "High priority access",
    "mt-Access": "Mobile terminated access (response to paging)", "mo-Signalling": "Mobile originated signalling (attach, TAU, registration)",
    "mo-Data": "Mobile originated data", "delayTolerantAccess-v1020": "Delay tolerant access (IoT)",
    "mo-VoiceCall-v1280": "Mobile originated voice call", "mo-VoiceCall": "Mobile originated voice call",
    "mo-VideoCall": "Mobile originated video call", "mo-SMS": "Mobile originated SMS",
    "mps-PriorityAccess": "MPS priority access", "mcs-PriorityAccess": "MCS priority access",
    "mo-ExceptionData-r13": "MO exception data (IoT)",
}

AP_RADIO_CAUSES = {
    "radio-connection-with-ue-lost": "eNB / gNB lost the radio link to the UE (RLF without re-establishment).",
    "user-inactivity": "Normal release after data inactivity.",
    "release-due-to-eutran-generated-reason": "eNB released the UE for an internal reason.",
    "release-due-to-ngran-generated-reason": "gNB released the UE for an internal reason.",
    "ho-failure-in-target-EPC-eNB-or-target-system": "Handover failed in the target eNB or system.",
    "handover-cancelled": "Handover was cancelled.",
    "tx2relocoverall-expiry": "X2 handover overall timer expired on the source.",
    "unknown-mme-ue-s1ap-id": "MME does not know the UE S1AP ID (context mismatch).",
    "unknown-enb-ue-s1ap-id": "eNB does not know the UE S1AP ID (context mismatch).",
    "failure-in-radio-interface-procedure": "A radio procedure (for example RRC reconfiguration) failed.",
    "radio-resources-not-available": "No radio resources (admission control).",
    "interaction-with-other-procedure": "Collision with another procedure.",
    "cs-fallback-triggered": "UE context released for CS fallback.",
    "ue-not-available-for-ps-service": "UE not available for PS service (for example during CS call).",
    "successful-handover": "Normal release after successful handover.",
    "normal-release": "Normal release requested by the UE or core.",
    "authentication-failure": "NAS authentication failed.",
    "detach": "UE detached.",
    "deregister": "UE de-registered.",
    "unspecified": "No specific cause given.",
}
